export {}; // make this file a module so top-level names do not clash across specs
// Generated by Cypress Author on 2026-10-09.
// Sentry keys only, with a site that sends traces: Sentry lists the pages itself and supplies sampled
// page loads, web vitals and errors. Nothing New Relic-only (load time, Apdex, status) may appear, a sampled
// count is always labelled as sampled, and a value nobody measured is "—", never 0.
// The API is stubbed (FAKE fixtures only) in the shape /api/metrics sends.
const at = "2026-01-01T00:00:00.000Z";
const SOURCES = { pages: "sentry", traffic: "sentry", vitals: "sentry", errors: "sentry" };
const latest = [{ title: "FAKE TypeError: x is undefined", count: 2, lastSeen: at }];

const page = (name: string, url: string, visitors: string, metrics: object) => ({ name, slug: url.replace(/^\//, "").replace(/\//g, "-"), url, visitors, recordedAt: at, metrics, byTool: { sentry: metrics } });
const pages = [
  // Loaded nine times, with two errors. INP is absent: no interaction was recorded.
  page("FAKE Blog", "/blog", "9", { traffic: { count: 9, sampled: true }, vitals: { lcp: 600, cls: 0.05, ttfb: 30 }, errors: { count: 2, latest } }),
  // Loaded, no errors and no CLS measured.
  page("FAKE Docs", "/docs", "3", { traffic: { count: 3, sampled: true }, vitals: { lcp: 400, ttfb: 20 }, errors: { count: 0, latest: [] } }),
  // Errors only: no sampled load, so no traffic and no vitals.
  page("FAKE Cart", "/cart", "0", { errors: { count: 7, latest: [{ title: "FAKE Error: z", count: 7, lastSeen: at }] } }),
];

const headers = (expected: string[]) => cy.get("thead th").should(($th) => expect([...$th].map((th) => th.innerText.trim())).to.deep.equal(expected));
// The Page cell reads as its link's title (the name); the path and a hidden ", view page details" are in it too.
const row = (i: number, expected: string[]) => cy.get("tbody tr").should(($tr) => expect([...$tr[i].children].map((td) => td.querySelector("a[title]")?.getAttribute("title") ?? (td as HTMLElement).innerText.trim())).to.deep.equal(expected));
// The first page of a run is slow on a cold server, so the wait is longer than Cypress's 4s default.
const shows = (...texts: string[]) => texts.forEach((t) => cy.contains(t, { timeout: 15000 }).should("be.visible"));
const absent = (...texts: string[]) => texts.forEach((t) => cy.contains(t).should("not.exist"));
const NEW_RELIC_ONLY = ["Avg Page Load Time", "Apdex", "Throughput", "Page views (24h)", "Avg Load Time", "Avg Load", "Healthy", "Warning", "Critical", "Visitors (24h)", "Traffic Volume", "Add New Relic keys"];

describe("Sentry keys only, site sending traces", () => {
  beforeEach(() => {
    cy.viewport(1440, 900); // sidebar labels and the header subtitle are hidden at narrower widths
    cy.intercept("GET", "/api/setup", { configured: true, tools: ["sentry"], keys: {} });
    cy.intercept("GET", "/api/metrics", { configured: true, tools: ["sentry"], failed: [], sources: SOURCES, project: "fake-project", pages, history: [{ timestamp: at, sources: SOURCES, pages }] }).as("metrics");
    cy.intercept("GET", "/api/timings", { items: [] });
    cy.intercept("POST", "/api/analyze", { alerts: [], recommendations: [] });
  });

  it("home → sampled page loads and web vitals, nothing that only New Relic measures", () => {
    cy.visit("/");
    cy.wait("@metrics");
    shows("Sampled page loads (24h)", "TTFB", "LCP", "CLS");
    cy.contains("Sampled page loads (24h)").parent().should("contain", "12");
    cy.contains("header p", "3 of 3 pages reporting · 12 sampled page loads in 24h · 9 open errors").should("be.visible");
    absent(...NEW_RELIC_ONLY, "views in 24h");
  });

  it("performance → pages listed from Sentry with a sampled column and no status", () => {
    cy.visit("/performance");
    cy.wait("@metrics");
    shows("Pages Reporting", "3 of 3", "Open Errors");
    cy.get("thead th").should(($th) => expect([...$th].map((th) => th.innerText.replace(/\s+/g, " ").trim())).to.deep.equal(["Page", "Sentry errors last 24h, no limit", "Page loads (sampled)"]));
    // Worst first: by Sentry errors, as nothing has a status.
    row(0, ["FAKE Cart", "7", "—"]); // errors only: no page load was sampled, so no number
    row(1, ["FAKE Blog", "2", "9"]);
    row(2, ["FAKE Docs", "0", "3"]);
    cy.get("tbody tr").should(($tr) => expect([...$tr].map((tr) => tr.querySelector("th span[title]")?.textContent)).to.deep.equal(["/cart", "/blog", "/docs"]));
    cy.get('[data-slot="alert"]').should("not.exist"); // no status, so nothing to alert on
    absent(...NEW_RELIC_ONLY);
  });

  it("page detail → sampled page loads and related errors only", () => {
    cy.visit("/performance/blog");
    cy.wait("@metrics");
    shows("Page loads (sampled)", "Related Errors", "FAKE TypeError: x is undefined");
    absent("Average Load Time", "Error Rate", ...NEW_RELIC_ONLY);
  });

  it("Sentry tab → its own page loads and vitals, with a dash where nothing was measured", () => {
    cy.visit("/tools/sentry");
    cy.wait("@metrics");
    headers(["Page Name", "Path", "Errors", "Latest Error", "Last Seen", "Page loads (sampled)", "LCP", "TTFB", "CLS", "INP"]);
    cy.get("tbody tr").should(($tr) => {
      const cells = (i: number) => [...$tr[i].children].map((td) => (td as HTMLElement).innerText.trim());
      // Page loads, LCP, TTFB, CLS, INP are the last five cells.
      expect(cells(0).slice(-5)).to.deep.equal(["9", "600ms", "30ms", "0.05", "—"]);
      expect(cells(1).slice(-5)).to.deep.equal(["3", "400ms", "20ms", "—", "—"]);
      expect(cells(2).slice(-5)).to.deep.equal(["—", "—", "—", "—", "—"]);
      expect(cells(2).slice(0, 4)).to.deep.equal(["FAKE Cart", "/cart", "7", "FAKE Error: z"]);
    });
  });
});
